### ISSUE TITLE
Relative paths support

### ISSUE THREAD

**Issue by MythicManiac** [GarmOfGnipahellir/dvalin#2]
It looks like this BepInex plugins is expecting its files to be extracted to
```
BepInEx\plugins\Dvalin
```
and uses this path as a hardcoded path.

This leads to issues with some mod managers that create unique subdirectories to each package, in this case r2modman, which creates the following structure:
```
BepInEx\plugins\GarmOfGnipahellir-MapTable_Dvalin
```
and as such does not work.

It would be best if the plugin itself only depends on paths relative to the plugin file, instead of using hardcoded paths, thus solving the issue.

**Comment by MythicManiac** [comment]
For reference, that should be doable with

```cs
Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);
```

However I have not tested if this works as expected. I do know some other plugins do relative paths like this

**Comment by GarmOfGnipahellir** [comment]
Thank you for the report, I had a feeling this would come back to bite me.
