### ISSUE TITLE
Request/Prefab Hirachey

### ISSUE THREAD

**Issue by christoff-1992** [GarmOfGnipahellir/dvalin#5]
Can you share the prefab hirachey, I wouldnt mind looking at adding some game objects to Valheim myself but haven't messed around with importing game objects into existing games before.

I take it the prefab will need some of the existing Valheim scripts attaching to it? I have taken a look at the example you have for unity but as we cant redistribute the assemblies they have been correctly removed from the prefabs. However unless im missing somthing I also cant see a reference to what the file/script would have been.

Thanks in advance!

**Comment by GarmOfGnipahellir** [comment]
I'll find a way to keep the references intact, in the mean time:
![image](https://user-images.githubusercontent.com/24740578/109215457-79b9c080-77b3-11eb-9b62-729547da3ca7.png)

**Comment by christoff-1992** [comment]
amazing thanks for this! I have been working my way through the assets in valheim to try figure evreything out. Do you happen to know what tags peices need? I have been able to get snapping points to work but only one way. My object can snap to existing pices but I cant get existing pices to snap to my new object. I have a feeling I have my tags/layers set up incorrectly.
